# Generated by Django 2.2.3 on 2020-02-06 11:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pven', models.CharField(max_length=100, verbose_name='prod_ven')),
                ('prew', models.CharField(max_length=100, verbose_name='prod_rew')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pname', models.CharField(max_length=100, verbose_name='prod_name')),
                ('pprice', models.FloatField(verbose_name='prod_price')),
                ('pqty', models.IntegerField(verbose_name='prod_qty')),
                ('pcat', models.CharField(max_length=50, verbose_name='prod_cat')),
                ('vendorref', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apptwo.Vendor')),
            ],
        ),
    ]
