# Generated by Django 2.2.3 on 2020-02-06 11:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pincode', models.IntegerField(verbose_name='pincode')),
                ('city', models.CharField(max_length=100, verbose_name='adr_city')),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ename', models.CharField(max_length=100, verbose_name='emp_name')),
                ('esal', models.FloatField(verbose_name='emp_sal')),
                ('eage', models.IntegerField(verbose_name='emp_age')),
                ('epos', models.CharField(max_length=50, verbose_name='emp_pos')),
                ('ecomp', models.CharField(max_length=100, verbose_name='emp_cmp')),
                ('addressref', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appone.Address')),
            ],
        ),
    ]
